#!/usr/bin/env python
# Filename: class_utils.py 
"""
introduction:

authors: Huang Lingcao
email:huanglingcao@gmail.com
add time: 27 January, 2024
"""



import os,sys
from torch.utils.data.dataset import Dataset
import numpy as np
from PIL import Image
import re

code_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, code_dir)
import basic_src.io_function as  io_function
import datasets.vector_gpd as vector_gpd

class RSVectorDataset(Dataset):
    pass

class RSPatchDataset(Dataset):
    def __init__(self, image_path_list, image_labels, label_txt = 'label.txt', transform=None, test=False):
        self.img_list = image_path_list
        self.labels = image_labels

        label_list = [[item.split(',')[0], int(item.split(',')[1])] for item in io_function.read_list_from_txt(label_txt)]
        # arr_t = np.array(label_list).T
        label_list = np.array(label_list).T.tolist()    # switch the row and column
        self.transform = transform
        self.test = test

        self.classes = label_list[0]

    def __getitem__(self, index):
        im_path = self.img_list[index]
        label = self.labels[index]
        # im_path = os.path.join(self.data_root, 'Images', im_path0)
        im = Image.open(im_path)
        if self.transform is not None:
            im = self.transform(im)

        return im, label, im_path

    def __len__(self):
        return len(self.img_list)

def get_class_labels_from_vector_file(img_path_list, vector_path):
    # the img_path_list are those subImages, generated by "get_subImages.py", using the "vector_path"
    if vector_gpd.is_field_name_in_shp(vector_path,'class_int') is False:
        return [-1]*len(img_path_list)
    shp_label_list = vector_gpd.read_attribute_values_list(vector_path,'class_int')
    label_list = []
    for i_path in img_path_list:
        tmp = os.path.basename(i_path).split('_')[-1]
        idx =int(tmp.split('.')[0])
        label_list.append(shp_label_list[idx])
    return label_list

def get_file_list(input_dir, pattern, area_ini):
    file_list = io_function.get_file_list_by_pattern(input_dir, pattern)
    if len(file_list) < 1:
        raise ValueError('No files for processing, please check directory (%s) and pattern (%s) in %s'
                         % (input_dir, pattern, area_ini))
    return file_list

# copy from dem_common.py
def get_grid_id_from_path(item):
    return int(re.findall('grid\d+', os.path.basename(item))[0][4:])

def pair_raster_vecor_files_grid(vector_files, raster_files):
    # pair the vector and raster files for each grid based on information in file name
    # e.g. sel_regions_small_S2_SR_grid9226_8bit.tif  : dem_diffs_polygons_grid9226.gpkg
    raster_grid_nums = [get_grid_id_from_path(item) for item in raster_files]
    vector_grid_nums = [get_grid_id_from_path(item) for item in vector_files]

    raster_vector_pairs = {}
    # set vector files as base
    for idx, v_grid in enumerate(vector_grid_nums):
        if v_grid in raster_grid_nums:
            ref_idx = raster_grid_nums.index(v_grid)
            raster_vector_pairs[v_grid] = [vector_files[idx], raster_files[ref_idx]]

    return raster_vector_pairs


def compute_topk_acc(pred, targets, topk):
    """
    Computing top-k accuracy given prediction and target vectors.
    Args:
        pred:    Network prediction
        targets: Ground truth labels
        topk:    k value
    """
    topk = min(topk, pred.shape[1])
    _, pred = pred.topk(topk, 1, True, True)
    pred = pred.t()
    correct = pred.eq(targets.view(1, -1).expand_as(pred))
    hits_tag = correct[:topk].reshape(-1).float().sum(0)

    return hits_tag


def calculate_metrics(outputs, targets):
    """
    Computing top-1 and top-5 accuracy metrics.
    Args:
        outputs: Network outputs list
        targets: Ground truth labels
    """
    pred = outputs

    # Top-k prediction for TAg
    hits_tag_top5 = compute_topk_acc(pred, targets, 5)
    hits_tag_top1 = compute_topk_acc(pred, targets, 1)

    return hits_tag_top5.item(), hits_tag_top1.item()

if __name__ == '__main__':
    pass